import {
  FaRegFileAudio,
  FaRegFileImage,
  FaRegFileLines,
  FaRegFilePdf,
  FaRegFileVideo,
  FaRegFileWord,
  FaRegFilePowerpoint,
  FaRegFileExcel,
  FaRegFileCode,
  FaLaptopFile,
  FaRegFileZipper,
} from "react-icons/fa6";

export const useFileIcons = (size) => {
  const fileIcons = {
    pdf: <FaRegFilePdf size={size} color="#d93025" />,
    jpg: <FaRegFileImage size={size} color="#2e9e5b" />,
    jpeg: <FaRegFileImage size={size} color="#2e9e5b" />,
    png: <FaRegFileImage size={size} color="#2e9e5b" />,
    txt: <FaRegFileLines size={size} color="#5f6b7a" />,
    doc: <FaRegFileWord size={size} color="#2b579a" />,
    docx: <FaRegFileWord size={size} color="#2b579a" />,
    mp4: <FaRegFileVideo size={size} color="#e67e22" />,
    webm: <FaRegFileVideo size={size} color="#e67e22" />,
    mp3: <FaRegFileAudio size={size} color="#8e44ad" />,
    m4a: <FaRegFileAudio size={size} color="#8e44ad" />,
    zip: <FaRegFileZipper size={size} color="#c9a227" />,
    ppt: <FaRegFilePowerpoint size={size} color="#d24726" />,
    pptx: <FaRegFilePowerpoint size={size} color="#d24726" />,
    xls: <FaRegFileExcel size={size} color="#217346" />,
    xlsx: <FaRegFileExcel size={size} color="#217346" />,
    exe: <FaLaptopFile size={size} color="#0067c0" />,
    html: <FaRegFileCode size={size} color="#0078d4" />,
    css: <FaRegFileCode size={size} color="#0078d4" />,
    js: <FaRegFileCode size={size} color="#0078d4" />,
    php: <FaRegFileCode size={size} color="#0078d4" />,
    py: <FaRegFileCode size={size} color="#0078d4" />,
    java: <FaRegFileCode size={size} color="#0078d4" />,
    cpp: <FaRegFileCode size={size} color="#0078d4" />,
    c: <FaRegFileCode size={size} color="#0078d4" />,
    ts: <FaRegFileCode size={size} color="#0078d4" />,
    jsx: <FaRegFileCode size={size} color="#0078d4" />,
    tsx: <FaRegFileCode size={size} color="#0078d4" />,
    json: <FaRegFileCode size={size} color="#0078d4" />,
    xml: <FaRegFileCode size={size} color="#0078d4" />,
    sql: <FaRegFileCode size={size} color="#0078d4" />,
    csv: <FaRegFileCode size={size} color="#0078d4" />,
    md: <FaRegFileCode size={size} color="#0078d4" />,
    svg: <FaRegFileCode size={size} color="#0078d4" />,
  };

  return fileIcons;
};
